RUN --mount=src=scripts,dst=/scripts /scripts/install_x-tools.sh kindle
RUN --mount=src=scripts,dst=/scripts /scripts/install_x-tools.sh kindle5
RUN --mount=src=scripts,dst=/scripts /scripts/install_x-tools.sh kindlehf
RUN --mount=src=scripts,dst=/scripts /scripts/install_x-tools.sh kindlepw2
