#!/bin/bash

HOME=/home/ko

# shellcheck source=/dev/null
. /etc/bash_completion

XTOOLS=${HOME}/x-tools

for tc in "${XTOOLS}"/*/bin; do
    export PATH=$tc:$PATH
done

export PATH="${HOME}/.local/bin:${PATH}"

alias ls='ls --color=auto'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

mkcd() {
    mkdir -p "$*"
    cd "$*" || exit
}
